In [2]:
import pandas as pd

DATA_PATH = "/mnt/data/documents/certh/synth4bench/dataset.tsv"
df = pd.read_csv(DATA_PATH, sep='\t')
df

/tmp/ipykernel_73941/2976074375.py:4: DtypeWarning: Columns (0: Indel category) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH, sep='\t')

,Dataset,Coverage,Read_length,POS,REF,ALT,DP,AD,AF,AF Deviation,mut,Caller,Indel category,Variant type,Class
0,300_100,300,100,304,G,T,257,NaN,0.124514,-1.322957e-09,304:G:T,Freebayes,NaN,TV,TP
1,1000_100,1000,100,304,G,A,972,NaN,0.096708,NaN,304:G:A,Freebayes,NaN,TV,FN
2,300_100,300,100,304,G,T,257,NaN,0.124514,3.800000e-07,304:G:T,LoFreq,NaN,TV,TP
3,1000_100,1000,100,304,G,A,972,NaN,0.096708,-1.028820e-03,304:G:A,LoFreq,NaN,TV,TP
4,300_100,300,100,304,G,T,257,NaN,0.124514,-2.751362e-02,304:G:T,Mutect2,NaN,TV,TP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873515,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,Freebayes,diff POS,Indel,FN
5873516,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,LoFreq,diff POS,Indel,FN
5873517,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,Mutect2,diff POS,Indel,FN
5873518,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,VarDict,diff POS,Indel,FN
5873519,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,VarScan,diff POS,Indel,FN

In [8]:
for col in df.columns:
    print(col)

Dataset
Coverage
Read_length
POS
REF
ALT
DP
AD
AF
AF Deviation
mut
Caller
Indel category
Variant type
Class

In [3]:
df['Indel category'].unique()

<StringArray>
[nan, 'diff POS', 'diff REF', 'diff ALT']
Length: 4, dtype: str

In [4]:
df[df["Class"].isin(["FN"])]

,Dataset,Coverage,Read_length,POS,REF,ALT,DP,AD,AF,AF Deviation,mut,Caller,Indel category,Variant type,Class
1,1000_100,1000,100,304,G,A,972,NaN,0.096708,NaN,304:G:A,Freebayes,NaN,TV,FN
5,1000_100,1000,100,304,G,A,972,NaN,0.096708,NaN,304:G:A,Mutect2,NaN,TV,FN
10,3000_100,3000,100,305,G,A,2898,NaN,0.150449,NaN,305:G:A,Freebayes,NaN,TV,FN
20,300_100,300,100,314,G,A,262,NaN,0.133588,NaN,314:G:A,Freebayes,NaN,TV,FN
21,300_100,300,100,314,G,A,262,NaN,0.133588,NaN,314:G:A,LoFreq,NaN,TV,FN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873515,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,Freebayes,diff POS,Indel,FN
5873516,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,LoFreq,diff POS,Indel,FN
5873517,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,Mutect2,diff POS,Indel,FN
5873518,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,VarDict,diff POS,Indel,FN
5873519,5000_75,5000,75,19067,G,GT,115,1.0,0.008696,NaN,19067:G:GT,VarScan,diff POS,Indel,FN

In [5]:

df[df["Class"].isin(["FP"])]

,Dataset,Coverage,Read_length,POS,REF,ALT,DP,AD,AF,AF Deviation,mut,Caller,Indel category,Variant type,Class
34335,1000_50,1000,50,1,C,0,8,0.0,0.000,NaN,1:C:0,VarScan,NaN,Noise,FP
34336,3000_50,3000,50,1,C,0,16,0.0,0.000,NaN,1:C:0,VarScan,NaN,Noise,FP
34337,3000_75,3000,75,1,C,0,12,0.0,0.000,NaN,1:C:0,VarScan,NaN,Noise,FP
34338,3000_100,3000,100,1,C,0,11,0.0,0.000,NaN,1:C:0,VarScan,NaN,Noise,FP
34339,3000_150,3000,150,1,C,0,9,0.0,0.000,NaN,1:C:0,VarScan,NaN,Noise,FP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873323,5000_300,5000,300,18988,C,CTGTG,67,11.0,0.164,NaN,18988:C:CTGTG,Mutect2,diff POS,Indel,FP
5873331,5000_75,5000,75,18991,T,TTC,1460,113.0,0.076,NaN,18991:T:TTC,Mutect2,diff POS,Indel,FP
5873383,1000_150,1000,150,19004,CCT,C,16,3.0,0.222,NaN,19004:CCT:C,Mutect2,diff POS,Indel,FP
5873408,1000_150,1000,150,19007,T,TGC,15,3.0,0.235,NaN,19007:T:TGC,Mutect2,diff POS,Indel,FP
5873476,700_75,700,75,19041,T,TACAACAAAACTTTGCTGCCACTTGTGTGTCTC,59,5.0,0.114,NaN,19041:T:TACAACAAAACTTTGCTGCCACTTGTGTGTCTC,Mutect2,diff POS,Indel,FP

In [6]:

df[df["Class"].isin(["TP"])]

,Dataset,Coverage,Read_length,POS,REF,ALT,DP,AD,AF,AF Deviation,mut,Caller,Indel category,Variant type,Class
0,300_100,300,100,304,G,T,257,NaN,0.124514,-1.322957e-09,304:G:T,Freebayes,NaN,TV,TP
2,300_100,300,100,304,G,T,257,NaN,0.124514,3.800000e-07,304:G:T,LoFreq,NaN,TV,TP
3,1000_100,1000,100,304,G,A,972,NaN,0.096708,-1.028820e-03,304:G:A,LoFreq,NaN,TV,TP
4,300_100,300,100,304,G,T,257,NaN,0.124514,-2.751362e-02,304:G:T,Mutect2,NaN,TV,TP
6,300_100,300,100,304,G,T,257,NaN,0.124514,-3.413620e-03,304:G:T,VarDict,NaN,TV,TP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5872801,5000_50,5000,50,18890,C,CT,2415,5.0,0.002100,NaN,18890:C:CT,VarDict,NaN,Indel,TP
5873033,1000_300,1000,300,18925,A,AC,76,1.0,0.013000,NaN,18925:A:AC,VarScan,NaN,Indel,TP
5873100,3000_100,3000,100,18935,GG,G,1299,3.0,0.002300,NaN,18935:GG:G,VarDict,NaN,Indel,TP
5873371,3000_75,3000,75,19001,C,CT,934,1.0,0.001000,NaN,19001:C:CT,VarScan,NaN,Indel,TP
5873389,5000_75,5000,75,19004,CC,C,1549,5.0,0.003200,NaN,19004:CC:C,VarDict,NaN,Indel,TP

In [ ]:
# what is the meaning of NaN values of the AD
# AD is the number of reads supporting the non reference alelle frequency
# It is a metric derived by the ground truth
df[df["AD"].isna()]["Class"].unique()

<StringArray>
['TP', 'FN']
Length: 2, dtype: str

In [16]:
df[df["Class"].isin(["TP", "FN"])]["AD"].unique()

array([      nan, 1.000e+00, 3.000e+00, ..., 1.073e+03, 1.238e+03,
       1.239e+03], shape=(1105,))

In [ ]:
# if a caller detect a false positive variant, then we don't have AF ground truth meaning in our ground truth
# this variant isn't detected so af deviation is false
df[df["Class"].isin(["FP"])]["AF Deviation"].unique()

array([nan])

In [22]:
df["Indel category"].unique()

<StringArray>
[nan, 'diff POS', 'diff REF', 'diff ALT']
Length: 4, dtype: str

In [ ]:
# since AF is ground truth if it class is FP, shouldn't AF be NaN? It isn't so maybe that AF is the AF of the caller
df[df["Class"].isin(["FP"])]["AF"].unique()

array([0.      , 0.012   , 0.002   , ..., 0.054632, 0.049944, 0.04481 ],
      shape=(5675,))

In [ ]:
df["AF"].isna().unique() # it isn't NaN, so it should be the caller's

array([False])

In [5]:
df.isna().sum()

Dataset                 0
Coverage                0
Read_length             0
POS                     0
REF                     0
ALT                     0
DP                      0
AD                  34335
AF                      0
AF Deviation      5849381
mut                     0
Caller                  0
Indel category    5492009
Variant type            0
Class                   0
dtype: int64

In [9]:
df["POS"].unique()

array([  304,   305,   309, ..., 19028, 19030, 19072], shape=(19077,))

In [ ]:
df[df["Class"].isin(["FP"])].set_index(["Dataset", "Coverage", "Read_length", "REF", "ALT", "Caller"])
# what is ALT 0?
# if class is FP, are there some callers that were able to catch it?
# if there is a record of an FP due to a caller, while the rest don't register anything, can we assume that for that site
# the AF of the non registered callers is 0, meaning that there is no variant present? No that's wrong, it is different 
# claiming no variant present and 0 AF.

                                                                               POS  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan      1
3000_50  3000     50          C   0                                 VarScan      1
3000_75  3000     75          C   0                                 VarScan      1
3000_100 3000     100         C   0                                 VarScan      1
3000_150 3000     150         C   0                                 VarScan      1
...                                                                            ...
5000_300 5000     300         C   CTGTG                             Mutect2  18988
5000_75  5000     75          T   TTC                               Mutect2  18991
1000_150 1000     150         CCT C                                 Mutect2  19004
                              T   TGC                               Mutect2  19007
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2  19041

                                                                               DP  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan     8
3000_50  3000     50          C   0                                 VarScan    16
3000_75  3000     75          C   0                                 VarScan    12
3000_100 3000     100         C   0                                 VarScan    11
3000_150 3000     150         C   0                                 VarScan     9
...                                                                           ...
5000_300 5000     300         C   CTGTG                             Mutect2    67
5000_75  5000     75          T   TTC                               Mutect2  1460
1000_150 1000     150         CCT C                                 Mutect2    16
                              T   TGC                               Mutect2    15
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2    59

                                                                                AD  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan    0.0
3000_50  3000     50          C   0                                 VarScan    0.0
3000_75  3000     75          C   0                                 VarScan    0.0
3000_100 3000     100         C   0                                 VarScan    0.0
3000_150 3000     150         C   0                                 VarScan    0.0
...                                                                            ...
5000_300 5000     300         C   CTGTG                             Mutect2   11.0
5000_75  5000     75          T   TTC                               Mutect2  113.0
1000_150 1000     150         CCT C                                 Mutect2    3.0
                              T   TGC                               Mutect2    3.0
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2    5.0

                                                                                AF  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan  0.000
3000_50  3000     50          C   0                                 VarScan  0.000
3000_75  3000     75          C   0                                 VarScan  0.000
3000_100 3000     100         C   0                                 VarScan  0.000
3000_150 3000     150         C   0                                 VarScan  0.000
...                                                                            ...
5000_300 5000     300         C   CTGTG                             Mutect2  0.164
5000_75  5000     75          T   TTC                               Mutect2  0.076
1000_150 1000     150         CCT C                                 Mutect2  0.222
                              T   TGC                               Mutect2  0.235
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2  0.114

                                                                             AF Deviation  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan           NaN
3000_50  3000     50          C   0                                 VarScan           NaN
3000_75  3000     75          C   0                                 VarScan           NaN
3000_100 3000     100         C   0                                 VarScan           NaN
3000_150 3000     150         C   0                                 VarScan           NaN
...                                                                                   ...
5000_300 5000     300         C   CTGTG                             Mutect2           NaN
5000_75  5000     75          T   TTC                               Mutect2           NaN
1000_150 1000     150         CCT C                                 Mutect2           NaN
                              T   TGC                               Mutect2           NaN
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2           NaN

                                                                                                                   mut  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan                                      1:C:0
3000_50  3000     50          C   0                                 VarScan                                      1:C:0
3000_75  3000     75          C   0                                 VarScan                                      1:C:0
3000_100 3000     100         C   0                                 VarScan                                      1:C:0
3000_150 3000     150         C   0                                 VarScan                                      1:C:0
...                                                                                                                ...
5000_300 5000     300         C   CTGTG                             Mutect2                              18988:C:CTGTG
5000_75  5000     75          T   TTC                               Mutect2                                18991:T:TTC
1000_150 1000     150         CCT C                                 Mutect2                                19004:CCT:C
                              T   TGC                               Mutect2                                19007:T:TGC
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2  19041:T:TACAACAAAACTTTGCTGCCACTTGTGTGTCTC

                                                                            Indel category  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan            NaN
3000_50  3000     50          C   0                                 VarScan            NaN
3000_75  3000     75          C   0                                 VarScan            NaN
3000_100 3000     100         C   0                                 VarScan            NaN
3000_150 3000     150         C   0                                 VarScan            NaN
...                                                                                    ...
5000_300 5000     300         C   CTGTG                             Mutect2       diff POS
5000_75  5000     75          T   TTC                               Mutect2       diff POS
1000_150 1000     150         CCT C                                 Mutect2       diff POS
                              T   TGC                               Mutect2       diff POS
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2       diff POS

                                                                            Variant type  \
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan        Noise
3000_50  3000     50          C   0                                 VarScan        Noise
3000_75  3000     75          C   0                                 VarScan        Noise
3000_100 3000     100         C   0                                 VarScan        Noise
3000_150 3000     150         C   0                                 VarScan        Noise
...                                                                                  ...
5000_300 5000     300         C   CTGTG                             Mutect2        Indel
5000_75  5000     75          T   TTC                               Mutect2        Indel
1000_150 1000     150         CCT C                                 Mutect2        Indel
                              T   TGC                               Mutect2        Indel
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2        Indel

                                                                            Class
Dataset  Coverage Read_length REF ALT                               Caller
1000_50  1000     50          C   0                                 VarScan    FP
3000_50  3000     50          C   0                                 VarScan    FP
3000_75  3000     75          C   0                                 VarScan    FP
3000_100 3000     100         C   0                                 VarScan    FP
3000_150 3000     150         C   0                                 VarScan    FP
...                                                                           ...
5000_300 5000     300         C   CTGTG                             Mutect2    FP
5000_75  5000     75          T   TTC                               Mutect2    FP
1000_150 1000     150         CCT C                                 Mutect2    FP
                              T   TGC                               Mutect2    FP
700_75   700      75          T   TACAACAAAACTTTGCTGCCACTTGTGTGTCTC Mutect2    FP

[120515 rows x 9 columns]

In [31]:
display(df["REF"].unique())
display(df["ALT"].unique())

<StringArray>
[                 'G',                  'C',                  'T',
                  'A',                 'TT',                 'CC',
                 'AA',                'CCT',                 'GG',
                 'TG',
 ...
             'GTGATC',            'GCTTACT',          'AGCCTTTGC',
           'GCCTTTGC',          'TGCCTCCCC',            'TCCCCGG',
             'CCCCGG', 'CCGGCTCGAGCAGTCCTG',             'AGTCCT',
           'CACAGGTT']
Length: 5192, dtype: str

<StringArray>
[                                'T',                                 'A',
                                 'C',                                 'G',
                                 '0',                                'AG',
                                'GG',                                'GT',
                                'CT',                                'CA',
 ...
                           'CACGGTG',                            'CACGGT',
                           'CACGGTC',                        'AGTCGGCCAC',
                           'TAGGATA',                           'GGATAAG',
                            'GGACTT',                            'GGATTT',
                         'TGACATGGG', 'TACAACAAAACTTTGCTGCCACTTGTGTGTCTC']
Length: 17568, dtype: str

We would like to build a classifier that given a vcf from one of that given callers, and after
post-processing it to filter the features found in our dataset, we would be able to verify/estimate
via the ML model the credibility of the variant findings.

1. First filter the models to include the records that included caller information. Thus classes in TN and FN aren't relevant because callers output only the variants that they spotted, so for the negative case, absense of variant, there isn't information of the callers in the first place.
2. Based on neomutate feature selection, we can be based on what to use.

Features for our xdgboost approach:
- is_snv_indel
- is_transcrption_tranversion
- Coverage
- Read length
- DP
- AF
- Caller

POS, REF, ALT are dropped. POSITION is volatile, references at test time will be different, won't be a valuable info. REF, ALT information is encoded via is_transcription_transversion based on neomutate. Similalry categoration of SNV, Indel, is integrated with is_snv_indel.

What would be the benefit to encode within one variable all the transversion, transition, insertion, delettion, instead of splitting in two broad categories, one snv_indel and the other identifying insertion, deletcion, transition or transversion based on the parent category. How this can benefit or not the model?

I think Read length should be dropped as well? Why it could be important info how many letters exist on the read, it can be related maybe with the quality aspect. I could do an ablation study for it maybe.

In our approach since the caller will be a decision making node, effectively the model won't be able to leverage information across model. It would be able to detect per caller, the vulnerabilities that it may have across the different features that will be used. For example it could detect that for specific coverage, af could lead to a less confident evaluation. An ensemble ml approach would be able to leverage the cross caller functionality to increase the accuracy, but not estimating the confidence of the prediction of the caller.